[package]
name = "zenoh-d435i-subscriber"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bincode = "2.0.1"
bytemuck = "1.23.0"
features = "0.10.0"
ndarray = "0.16.1"
rerun = "0.23.2"
serde = { version = "1.0.219", features = ["derive"] }
tokio = "1.45.0"
zenoh = "1.3.4"
