[package]
name = "zenoh-d435i-subscriber"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
features = "0.10.0"
serde = { version = "1.0.219", features = ["derive"] }
tokio = "1.45.0"
zenoh = "1.3.4"
